# Funding links for the Omni-Dromenon Engine organization
# These links will appear in the "Sponsor" button on all org repositories

# GitHub Sponsors username(s)
github: [ivviiviivvi]

# Other funding platforms (uncomment when configured)
# ko_fi: omnidromenon
# patreon: omnidromenon
# open_collective: omni-dromenon-engine

# Custom funding URLs
# custom: ["https://omni-dromenon-engine.org/support"]
