FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY syntax.css /usr/share/nginx/html/syntax.css
RUN chmod 644 /usr/share/nginx/html/index.html /usr/share/nginx/html/styles.css /usr/share/nginx/html/syntax.css
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
