apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: omni-dromenon-core
  namespace: default
  labels:
    app: omni-dromenon
    component: core-engine
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: omni-dromenon-service-account
      containers:
      - image: gcr.io/PROJECT_ID/omni-dromenon-core:latest
        name: core-engine
        ports:
        - name: http1
          containerPort: 3000
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: omni-redis-url
              key: url
        - name: FIRESTORE_PROJECT_ID
          value: PROJECT_ID
        - name: GCP_REGION
          value: "us-central1"
        - name: CORS_ORIGIN
          value: "https://omni-dromenon-engine.com,https://www.omni-dromenon-engine.com"
        
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /app/config
          readOnly: true
      
      volumes:
      - name: tmp
        emptyDir: {}
      - name: config
        secret:
          secretName: omni-core-config
      
      timeoutSeconds: 600
      maxSurge: 1
  
  traffic:
  - percent: 100
    latestRevision: true
---
apiVersion: v1
kind: Service
metadata:
  name: omni-dromenon-core-lb
  labels:
    app: omni-dromenon
    component: core-engine
spec:
  type: LoadBalancer
  selector:
    app: omni-dromenon
    component: core-engine
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 3000
    protocol: TCP
---
apiVersion: autoscaling.knative.dev/v1alpha1
kind: KPA
metadata:
  name: omni-dromenon-core-autoscale
spec:
  scaleTargetRef:
    kind: Service
    name: omni-dromenon-core
  minReplicas: 1
  maxReplicas: 10
  targetUtilization: 0.7
